
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('skill_cards').del()
    .then(()=> {
      return knex('skill_cards').insert([
        {id: 1, title: 'Cuddeling', description: 'Cuddeling is an important part of life. I take cuddeling very seriously, and can teach you how to do it right.',  photo: 'http://img.huffingtonpost.com/asset/scalefit_600_noupscale/564224fc14000069023ca5d3.jpeg', user_id: 9, categories_id: 14, environment_id: 5, contact: 'user@example.com'},
        {id: 2, title: 'Dancing', description: 'Do people tell you that you have less rhythm than a bread stick? I can teach you how to dance like a groovy master',  photo: 'https://upload.wikimedia.org/wikipedia/commons/3/38/Two_dancers.jpg', user_id: 4, categories_id: 3, environment_id: 3, contact: 'user@example.com' },
        {id: 3, title: 'LED lighting', description: 'You can easily create basic electronics centered around LED\'s. Who doesn\'t love LED\'s?',  photo:'https://cdn-learn.adafruit.com/guides/images/000/000/206/medium800/LEDrainbow.jpg?1448301167', user_id: 4, categories_id: 7, environment_id: 4, contact: 'user@example.com'},
        {id: 4, title: 'Knots', description: 'Knots are super useful, but they\'re also fun! Learn how to properly tie kots so that your rope holds and doesn\'t get tangeled.',  photo:'http://www.animatedknots.com/imagesindex/typestopperstop1.png', user_id: 1, categories_id: 8, environment_id: 3, contact: 'user@example.com'},
        {id: 5, title: 'Being annoying', description: 'Are you tired of people lingering around too long? I\'m offering the most successfull techniques for being annoying to get rid of those around you',  photo: 'http://i.huffpost.com/gen/1360695/images/o-ANNOYING-COWORKER-facebook.jpg', user_id: 2, categories_id: 4, environment_id: 5, contact: 'user@example.com'},
        {id: 6, title: 'Yogging', description: 'Run like Ron Bergandy. Yogging, with a hard Y, is a serioud physical endeavour.',  photo: 'https://squashskills.com/images/sized/1400x660/1063618794-poi824.290-qx100.png', user_id: 3, categories_id: 5, environment_id: 6, contact: 'user@example.com'},
        {id: 7, title: 'Self hair cutting', description: 'Are you tired of hair stylests always messing up your fresh hairdo? I cut my own hair,and can share personal techniques to make you a master of grooming yourself',  photo: 'https://www.allskins.co.uk/wp-content/uploads/2015/04/long-hair.jpg', user_id: 5, categories_id: 4, environment_id: 5, contact: 'user@example.com'},
        {id: 8, title: 'Competitive eating', description: 'It really is a talent, and I can help you ramp up to be the next champion at the local wings night',  photo: 'http://s4.thingpic.com/images/Ut/gzvfUSpv9hsxGRnXVZ6fHA1V.jpeg', user_id: 6, categories_id: 11, environment_id: 5, contact: 'user@example.com'},
        {id: 9, title: 'Tug-of-war', description: 'Are you tired of not pulling on the rope better than the other team? Join me for lessons on how to win at tug-of-war',  photo: 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Irish_600kg_euro_chap_2009.JPG', user_id: 7, categories_id: 5, environment_id: 6, contact: 'user@example.com'},
        {id: 10, title: 'Extreme positivity', description: 'Whether you are a debbie-downer, or just have a mildly sunny disposition, I can teach you the secrets of extreme positivity. Goodbye, Negative Nancy!',  photo: 'https://www.lakehouserecoverycenter.com/wp-content/uploads/2015/05/iStock_000011259011_Large.jpg', user_id: 10, categories_id: 14, environment_id: 5, contact: 'user@example.com'},
        {id: 11, title: 'Shakespeare interpretation', description: 'Learn how to read and interpret the classics like Hamlet and King Lear. Now you can be that snobby freind every summer at Shakespeare-in-the-park.',  photo: 'http://havlicek.weebly.com/uploads/6/8/5/2/685209/8100287.jpg?356', user_id: 1, categories_id: 1, environment_id: 5, contact: 'user@example.com'},
        {id: 12, title: 'Dog training', description: 'Teach your pup new tricks and impress your freinds at the dog park.',  photo:'https://www.cesarsway.com/sites/newcesarsway/files/styles/large_article_preview/public/5-essential-commands-you-can-teach-your-dog_1.jpg?itok=nYOp-YSR', user_id: 10, categories_id: 2, environment_id: 5, contact: 'user@example.com'},
        {id: 13, title: 'Tango', description: 'Join my tango group every Wednesday evening.',  photo: 'https://s-media-cache-ak0.pinimg.com/originals/23/0c/b2/230cb2f11cf1945535abf663bcb13d17.jpg', user_id: 10, categories_id: 3, environment_id: 5, contact: 'user@example.com'},
        {id:14, title: 'Outdoor leadership', description: 'Learn how to organize and guide groups in the backcountry.',  photo: 'http://www.motherearthnews.com/-/media/Images/MEN/Editorial/Articles/Magazine-Articles/1988/07-01/The-National-Outdoor-Leadership-School-Wilderness-Training/112-084-01.jpg', user_id: 10, categories_id:4, environment_id: 6, contact: 'user@example.com'},
        {id: 16, title: 'Water polo', description: 'I am a former  coach for the Jamaican olympic water polo team. Come learn the fundamentals of water polo.',  photo: 'http://www.nbcolympics.com/sites/default/files/styles/951x536_rectangle/public/field_image/08August2016/rio_olympics_water_po_webf_5.jpg?itok=L-lBdir7', user_id: 10, categories_id: 5, environment_id: 1, contact: 'user@example.com'},
        {id: 17, title: 'Yoga', description: 'Practicing yoga relaxes the body and sharpens the mind. I can help you with the more difficult poses',  photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXCXOHxNK0xC1BmRsFHDGf5Ze3XkGnbnapCLLl4WgI_P3CsIKIkA', user_id: 10, categories_id: 6, environment_id: 3, contact: 'user@example.com'},
        {id: 18, title: 'Foraging', description: 'An essential skill for survival and finding the best wild mushrooms and berries. Learn how to live in the wild just as our ancesters did.',  photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShS5dywjkz7msXx26IHRmPXYoobr7-9O4n5LfBAK60Lq1tfGAq', user_id: 10, categories_id: 8, environment_id: 7, contact: 'user@example.com'},
        {id: 19, title: 'Impressionist painting', description: 'Bring a brush and canvas and we\'ll go into the wild, where I can teach you to paint like Monet. I specialize in trees and ponds.', photo:'https://www.jacksonsart.com/blog/wp-content/uploads/2015/04/claude-monet-impression-sunrise.jpg', user_id: 10, categories_id: 9, environment_id: 7, contact: 'user@example.com'},
        {id: 20, title: 'Settlers!', description: 'I am a master at Settlers of Catan. There is no such thing as a bad board layout, only a bad strategy. I will teach you how to win any Settlers game!', photo:'http://www.boardgamequest.com/wp-content/uploads/2013/04/Settlers-of-Catan.jpg', user_id: 10, categories_id: 10, environment_id: 5, contact: 'user@example.com'},
        {id: 21, title: 'Dungeons & Dragons', description: 'I can teach you how to play D&D. I have great templates for character and story design.', photo:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqXPlHEYTWQmR04XiJJYTEROahDutqQFvoOinHYwLFjwIzy00Cvw', user_id: 10, categories_id: 12, environment_id: 5, contact: 'user@example.com'},
        {id: 22, title: 'Astrology and apple pie', description: 'Come hang out with our monthly astrology group. We stay up all night eating apple pie, observing the heavans, and teaching each other about the constellations', photo:'http://astrostyle.com/wp-content/uploads/2013/10/learn-astrology-astrotwins.jpg', user_id: 10, categories_id: 14, environment_id: 8, contact: 'user@example.com'},
        {id: 23, title: 'Drag racing', description: 'Contact me for more information.', photo:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-zDp2P42qDBM2Wi__1tfoFcIh7rXU-ByPtdeZY0K3Pp1adIfb', user_id: 10, categories_id: 22, environment_id: 6, contact: 'user@example.com'},
        {id: 24, title: 'Wind sailing', description: 'There\'s a great lake near my house where I wind sail every Saturday. Come down and I\'ll teach you how!.', photo:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2uwMUQdXK0bepqcJGdFHTZYcswvoGl_oi2EFXxM0v_F3KRmNeLQ', user_id: 10, categories_id: 5, environment_id: 2, contact: 'user@example.com'},
        {id: 25, title: 'Paleo dieting', description: 'Eat like a wild beast to get in shape and be healthier.', photo:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReEF5e5em9WdXhPi3X8PUbi1m7s6Yxc1_duKHabFxEuRUokBHHTw', user_id: 10, categories_id: 21, environment_id: 5, contact: 'user@example.com'},
        {id: 26, title: 'Eyeliner expert', description: 'Girl or guy, I can teach you the tricks of applying eyeliner perfectly. No more mess.', photo:'https://www.google.com/search?q=eye+liner+on+man&rlz=1C5CHFA_enUS739US739&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiv3Knc7MLUAhXBJCYKHdMiChQQ_AUIBigB&biw=1270&bih=611#tbm=isch&q=carl+drogo&imgrc=JP358Bfx-t8xIM:', user_id: 10, categories_id: 20, environment_id: 5, contact: 'user@example.com'},
        {id: 27, title: 'German beer brewing', description: 'Come join the beer-garten community, and learn how to brew authentic German Pilsner.', photo:'http://craftbeverageinsights.com/wp-content/uploads/2016/01/beer-and-brewing.jpg', user_id: 10, categories_id: 19, environment_id: 8, contact: 'user@example.com'}
      ]);
    })
    .then(function(){
    return knex.raw("SELECT setval('skill_cards_id_seq', (SELECT MAX(id) FROM skill_cards))");
  });
};
